
# tap repositories and their packages

tap homebrew/core
brew agda
brew ansible
brew apr
brew apr-util
brew arpack
brew autoconf
brew autoconf-archive
brew automake
brew boost
brew brotli
brew c-ares
brew cabal-install
brew cairo
brew cmigemo
brew eigen
brew emacs
brew epstool
brew ffmpeg
brew fftw
brew fig2dev
brew flac
brew fltk
brew fontconfig
brew fontforge
brew freetype
brew fribidi
brew gcc
brew gd
brew gdbm
brew gdk-pixbuf
brew gettext
brew ghc
brew ghostscript
brew giflib
brew git
brew gl2ps
brew glib
brew glpk
brew gmp
brew gnu-sed
brew gnuplot --with-aquaterm
brew gnutls
brew gradle
brew graphicsmagick
brew graphite2
brew graphviz
brew harfbuzz
brew hdf5
brew httpd
brew icu4c
brew ilmbase
brew imagemagick
brew imagemagick@6
brew isl
brew jansson
brew jasper
brew jemalloc
brew jpeg
brew lame
brew leptonica
brew libcroco
brew libev
brew libevent
brew libffi
brew libmpc
brew libogg
brew libpng
brew librsvg
brew libsndfile
brew libspiro
brew libtasn1
brew libtiff
brew libtool
brew libuninameslist
brew libunistring
brew libvorbis
brew libvpx
brew libyaml
brew little-cms2
brew lua
brew markdown
brew mas
brew mecab
brew mecab-ipadic
brew mercurial
brew metis
brew mpfr
brew mysql@5.7
brew ncurses
brew netpbm
brew nettle
brew nghttp2
brew node
brew nspr
brew nss
brew numpy
brew octave
brew open-mpi
brew openblas
brew opencv
brew openexr
brew openjpeg
brew openssl
brew opus
brew p11-kit
brew p7zip
brew pango
brew pcre
brew pcre2
brew pixman
brew pkg-config
brew plotutils
brew poppler
brew portaudio
brew pstoedit
brew pyenv
brew pyenv-virtualenv
brew python
brew python@2
brew qhull
brew qrupdate
brew r
brew readline
brew sdl2
brew snappy
brew sqlite
brew suite-sparse
brew sundials
brew szip
brew tbb
brew tesseract
brew texinfo
brew theora
brew tmux
brew tree
brew veclibfort
brew webp
brew wtf
brew x264
brew x265
brew xvid
brew xz
brew zsh
brew zsh-completions

tap homebrew/cask-fonts
cask font-ricty-diminished

tap homebrew/cask
cask aquaterm
cask java
cask ngrok
cask skim
cask virtualbox

tap rcmdnk/file
brew brew-file

tap sanemat/font
brew ricty --with-powerline

# Other Cask applications
cask dropbox
cask font-source-code-pro
cask mactex
cask rstudio
cask sourcetree
cask xquartz

# App Store applications
appstore 409183694 Keynote (8.2)
appstore 539883307 LINE (5.10.1)
appstore 409203825 Numbers (5.2)
appstore 409201541 Pages (7.2)
appstore 803453959 Slack (3.3.3)
appstore 1278508951 Trello (2.10.7)
appstore 485812721 TweetDeck (3.9.889)
appstore 497799835 Xcode (10.1)
