#!/bin/sh

if git_status=$(cd $1 && git status 2>/dev/null ); then
    git_branch="$(echo $git_status| awk 'NR==1 {print $3}')"
    case $git_status in
        *Changes\ not\ staged* ) state="#[bg=colour013,fg=black]± #[fg=default]" ;;
        *Changes\ to\ be\ committed* ) state="#[bg=blue,fg=black]↑ #[default]" ;; 
        * ) state="#[bg=green,fg=black] ✔ #[default]" ;;
    esac
    if [[ $git_branch = "master" ]]; then
        git_info="#[bg=black,fg=blue]  ${git_branch} ${state}#[default]"
    else
        git_info="#[bg=black,fg=colour014]  ${git_branch} ${state}#[default]"
    fi
else
    git_info=""
fi

directory="#[bg=black,fg=cyan]$1#[default]"

echo "$directory$git_info"
